/*
 * Copyright (c) 2012 Tyler Treat
 * 
 * This file is part of Infinitum Framework.
 *
 * Infinitum Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Infinitum Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Infinitum Framework.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.clarionmedia.infinitum.orm;

import com.clarionmedia.infinitum.orm.annotation.Entity;
import com.clarionmedia.infinitum.orm.annotation.Persistence;

/**
 * <p>
 * Abstract base class from which all domain or model classes inherit from.
 * Particularly, persistent classes need to extend this in order to utilize the
 * framework's lightweight ORM.
 * </p>
 * 
 * @author Tyler Treat
 * @version 1.0 02/11/12
 */
@Entity
public abstract class AbstractModel {

	@Persistence
	protected long mId;

	/**
	 * Returns this model's ID. The ID is what is used as the primary key for
	 * this record in the backing datastore. Thus, this value is unique per
	 * type.
	 * 
	 * @return the ID of this model
	 */
	public long getId() {
		return mId;
	}

	/**
	 * Sets the value of this model's ID. This is typically only used by the
	 * Infinitum ORM as primary keys are usually generated by the database.
	 * 
	 * @param id
	 *            the value to set as this model's ID
	 */
	public void setId(long id) {
		mId = id;
	}

}
